# Generated by Django 5.1 on 2024-08-20 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='data_of_birthday',
            new_name='date_of_birthday',
        ),
    ]
