# Generated by Django 5.1 on 2024-08-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_rename_data_of_birthday_author_date_of_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birthday',
            field=models.DateField(),
        ),
    ]
