# Generated by Django 5.1 on 2024-09-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=False),
        ),
    ]
