# Generated by Django 5.1 on 2024-09-09 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_alter_ad_managers_remove_author_surname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ad',
            new_name='Post',
        ),
        migrations.RenameModel(
            old_name='ResponseAd',
            new_name='Responses',
        ),
    ]
