# Generated by Django 5.1 on 2024-09-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_rename_ad_post_rename_responsead_responses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='date_of_birthday',
        ),
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='author',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Мужской'), ('Female', 'Женский')], max_length=10),
        ),
    ]
