# Generated by Django 5.1 on 2024-09-09 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_alter_post_author_alter_post_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='awards',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 9, 20, 44, 39, 56997, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
