# Generated by Django 5.1 on 2024-09-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_post_awards_post_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='requirements',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
