# Generated by Django 5.1 on 2024-09-09 20:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_post_requirements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Players',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='player',
        ),
    ]
