# Generated by Django 5.1 on 2024-09-09 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0020_rename_author_players_rename_author_post_player'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='responses',
            old_name='author',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='responses',
            old_name='ad',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='players',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='board.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='board.players'),
        ),
    ]
