# Generated by Django 5.1 on 2024-09-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0021_rename_author_responses_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='level',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
