# Generated by Django 5.1 on 2024-09-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0022_players_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
