# Generated by Django 5.1 on 2024-09-10 17:22

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0023_alter_players_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='post',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('is_published', models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=False)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('awards', models.CharField(max_length=255, null=True)),
                ('requirements', models.CharField(max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='board.category')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='board.players')),
            ],
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='responses',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resp', to='board.event'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
