# Generated by Django 5.1 on 2024-09-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0024_remove_responses_post_event_responses_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='requirements',
        ),
        migrations.AddField(
            model_name='event',
            name='requirement_level',
            field=models.IntegerField(default=0),
        ),
    ]
