# Generated by Django 5.1 on 2024-09-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0025_remove_event_requirements_event_requirement_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
