# Generated by Django 5.1 on 2024-09-10 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0026_event_time_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resp', to='board.event'),
            preserve_default=False,
        ),
    ]
