# Generated by Django 5.1 on 2024-09-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0028_players_guild'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(related_name='events', to='board.category'),
        ),
    ]
