# Generated by Django 5.1 on 2024-09-10 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0031_rename_events_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='guild',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='player', to='board.category'),
        ),
    ]
