# Generated by Django 5.1 on 2024-09-11 00:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0032_alter_players_guild'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='players',
            options={'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterModelOptions(
            name='responses',
            options={'verbose_name': 'Отклик', 'verbose_name_plural': 'Отклики'},
        ),
        migrations.AddField(
            model_name='responses',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата отклика'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='awards',
            field=models.CharField(max_length=255, null=True, verbose_name='Ожидаемые награды за событие'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(related_name='events', to='board.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=False, verbose_name='Этап публикации'),
        ),
        migrations.AlterField(
            model_name='event',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='board.players', verbose_name='Автор объявления'),
        ),
        migrations.AlterField(
            model_name='event',
            name='requirement_level',
            field=models.IntegerField(default=0, verbose_name='Рекомендуемый уровень'),
        ),
        migrations.AlterField(
            model_name='event',
            name='text',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='players',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='players',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город проживания'),
        ),
        migrations.AlterField(
            model_name='players',
            name='guild',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='player', to='board.category', verbose_name='Гильдия'),
        ),
        migrations.AlterField(
            model_name='players',
            name='level',
            field=models.IntegerField(default=0, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='players',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='players',
            name='sex',
            field=models.CharField(choices=[('Male', 'Мужской'), ('Female', 'Женский')], max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='players',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='responses',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resp', to='board.event', verbose_name='Событие/объявление'),
        ),
        migrations.AlterField(
            model_name='responses',
            name='message',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='responses',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resp', to='board.players', verbose_name='Игрок'),
        ),
    ]
