# Generated by Django 5.1 on 2024-09-11 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0033_alter_event_options_alter_players_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelManagers(
            name='event',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Slug категории'),
        ),
        migrations.AlterField(
            model_name='players',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город проживания'),
        ),
        migrations.AlterField(
            model_name='players',
            name='guild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player', to='board.category', verbose_name='Гильдия'),
        ),
    ]
