# Generated by Django 5.1 on 2024-09-11 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0034_alter_category_options_alter_event_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='guild',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='player', to='board.category', verbose_name='Гильдия'),
            preserve_default=False,
        ),
    ]
