# Generated by Django 5.1 on 2024-09-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0035_alter_players_guild'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='rating',
            field=models.FloatField(default=0.0, max_length=5.0, verbose_name='Рейтинг игрока'),
        ),
    ]
