# Generated by Django 5.1 on 2024-09-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0036_players_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='awards',
            field=models.TextField(default=None, null=True, verbose_name='Ожидаемые награды за событие'),
        ),
    ]
