# Generated by Django 5.1 on 2024-09-14 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0037_alter_event_awards'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='registration_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
