# Generated by Django 5.1 on 2024-09-17 06:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0039_rename_event_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='awards',
            field=models.TextField(default=None, null=True, validators=[django.core.validators.MinLengthValidator(50, message='Минимально допустимое количество символов: 100!')], verbose_name='Ожидаемые награды за событие'),
        ),
        migrations.AlterField(
            model_name='post',
            name='requirement_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Минимально допустимый уровень: 0!'), django.core.validators.MaxValueValidator(50, message='Максимально допустимый уровень: 50!')], verbose_name='Рекомендуемый уровень'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(100, message='Минимально допустимое количество символов: 100!')], verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10, message='Минимально допустимое количество символов: 50!'), django.core.validators.MaxLengthValidator(100, message='Максимально допустимое количество символов: 100!')], verbose_name='Заголовок'),
        ),
    ]
