# Generated by Django 5.1 on 2024-09-17 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0040_alter_post_awards_alter_post_requirement_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=None, null=True, validators=[django.core.validators.MinLengthValidator(5, message='Минимально допустимое количество символов: 0!'), django.core.validators.MaxLengthValidator(50, message='Максимально допустимое количество символов: 50!')], verbose_name='slug объявления'),
        ),
        migrations.AlterField(
            model_name='post',
            name='awards',
            field=models.TextField(default=None, null=True, validators=[django.core.validators.MinLengthValidator(50, message='Минимально допустимое количество символов: 100!')], verbose_name='Награды за событие'),
        ),
    ]
