# Generated by Django 5.1 on 2024-09-17 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0042_alter_category_slug_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='awards',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(50, message='Минимально допустимое количество символов: 50!')], verbose_name='Награды за событие'),
        ),
    ]
