# Generated by Django 5.1 on 2024-09-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0045_rename_post_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photo/%Y/%m/%d', verbose_name='Фото контент'),
        ),
        migrations.AddField(
            model_name='event',
            name='video',
            field=models.FileField(blank=True, default=None, null=True, upload_to='video/%Y/%m/%d', verbose_name='Видео контент'),
        ),
    ]
