# Generated by Django 5.1 on 2024-09-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0046_event_photo_event_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='video/%Y/%m/%d', verbose_name='Аватарка'),
        ),
    ]
