# Generated by Django 5.1 on 2024-09-23 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0050_alter_players_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Ошибка! Минимально допустимое значение: 0'), django.core.validators.MaxValueValidator(50, message='Ошибка! Максимально допустимое значение: 50')], verbose_name='Уровень'),
        ),
    ]
