# Generated by Django 5.1 on 2024-09-23 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0051_alter_players_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(14, message='Минимально допустимый возраст игрока 14 лет'), django.core.validators.MaxValueValidator(123, message='Вам не может быть столько лет!')], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='players',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(2, message='Ошибка! Минимально допустимое количество символов: 2'), django.core.validators.MaxLengthValidator(100, message='Ошибка! Максимально допустимое количество символов: 100')], verbose_name='Город проживания'),
        ),
        migrations.AlterField(
            model_name='players',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, message='Ошибка! Минимально допустимое количество символов: 2'), django.core.validators.MaxLengthValidator(100, message='Ошибка! Максимально допустимое количество символов: 100')], verbose_name='ФИО'),
        ),
    ]
