# Generated by Django 5.1 on 2024-09-23 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0053_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
