# Generated by Django 5.1 on 2024-09-24 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0054_delete_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.MinLengthValidator(5, message='Минимально допустимое количество символов: 5!'), django.core.validators.MaxLengthValidator(50, message='Максимально допустимое количество символов: 50!')], verbose_name='URL объявления'),
        ),
        migrations.AlterField(
            model_name='players',
            name='profile_picture',
            field=models.ImageField(default='photo/players/default/Аватарка по уомлчанию.jpg', upload_to='photo/players/%Y/%m/%d', verbose_name='Аватарка'),
        ),
    ]
