# Generated by Django 5.1 on 2024-09-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0055_alter_event_slug_alter_players_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='profile_picture',
            field=models.ImageField(default='photo/players/default/Аватарка по умолчанию.jpg', upload_to='photo/players/%Y/%m/%d', verbose_name='Аватарка'),
        ),
    ]
