# Generated by Django 5.1 on 2024-09-24 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0056_alter_players_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='message',
            field=models.CharField(max_length=100, verbose_name='Текст сообщения'),
        ),
        migrations.CreateModel(
            name='AnswertoResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100, verbose_name='Текст сообщения')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа на отклик')),
                ('resp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answers', to='board.responses', verbose_name='Отклик')),
            ],
            options={
                'verbose_name': 'Ответ на отклик',
                'verbose_name_plural': 'Ответы на отклик',
            },
        ),
    ]
