# Generated by Django 5.1 on 2024-09-24 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0057_alter_responses_message_answertoresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertoresponse',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='answers', to='board.players', verbose_name='Игрок'),
            preserve_default=False,
        ),
    ]
