# Generated by Django 5.1 on 2024-09-24 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0058_answertoresponse_player'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answertoresponse',
            options={'ordering': ['time_create'], 'verbose_name': 'Ответ на отклик', 'verbose_name_plural': 'Ответы на отклик'},
        ),
        migrations.AlterModelOptions(
            name='responses',
            options={'ordering': ['time_create'], 'verbose_name': 'Отклик', 'verbose_name_plural': 'Отклики'},
        ),
        migrations.AlterField(
            model_name='responses',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='resp', to='board.players', verbose_name='Игрок'),
        ),
    ]
