# Generated by Django 5.1 on 2024-09-29 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0059_alter_answertoresponse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertoresponse',
            name='resp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='board.responses', verbose_name='Отклик'),
        ),
    ]
