# Generated by Django 5.1 on 2024-09-29 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0060_alter_answertoresponse_resp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertoresponse',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='board.players', verbose_name='Игрок'),
        ),
        migrations.AlterField(
            model_name='responses',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resp', to='board.players', verbose_name='Игрок'),
        ),
    ]
