# Generated by Django 5.1 on 2024-10-01 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0061_alter_answertoresponse_player_alter_responses_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='is_taken',
            field=models.BooleanField(choices=[(False, 'Не принят'), (True, 'Принят')], default=False, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='players',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, message='Ошибка! Минимально допустимое количество символов: 2'), django.core.validators.MaxLengthValidator(100, message='Ошибка! Максимально допустимое количество символов: 100')], verbose_name='Имя'),
        ),
    ]
