# Generated by Django 5.1 on 2024-10-02 11:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordconfirm_registration_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PasswordConfirm',
            new_name='EmailConfirm',
        ),
    ]
