# Generated by Django 5.1 on 2024-10-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_username_emailconfirm_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailconfirm',
            options={'verbose_name': 'Код подтверждения', 'verbose_name_plural': 'Коды подтверждения'},
        ),
    ]
